version: "3.3"

services:
  app:
    container_name: app
    depends_on:
      - database
    build:
      context: ../../
      dockerfile: apps/api/Dockerfile
    ports:
      - 4000:4000
    env_file: ../../.env.production

  database:
    container_name: database
    image: postgres:12-alpine
    ports:
      - 5432:5432
    env_file: ./.env.database
    volumes:
      - ./data/postgres:/var/lib/postgresql/data

  database-dashboard:
    container_name: database-dashboard
    image: adminer:latest
    ports:
      - 8080:8080
